import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {networkInterfaces} from 'node:os';
import {WebSocketServer,WebSocket} from 'ws';
const PORT=Number(process.env.PORT)||3000,MAX=64;
const MAPS=[
[[0,0,3,2],[-8,-4,2,4],[8,4,2,4],[0,-8,5,1],[0,8,5,1]],
[[-6,-6,4,3],[6,-6,4,3],[-6,6,4,3],[6,6,4,3],[0,0,2,2]],
[[-8,0,1.4,7],[8,0,1.4,7],[0,-6,3,2],[0,6,3,2],[0,0,3,1]],
[[-5,-5,1,7],[5,5,1,7],[0,0,1,7],[-9,6,4,1],[9,-6,4,1]],
[[0,0,5,2],[-8,-7,2.5,2.5],[8,7,2.5,2.5],[-8,7,2.5,2.5],[8,-7,2.5,2.5]],
[[-5,0,3,2],[5,0,3,2],[0,-6,2,3],[0,6,2,3],[-10,-9,2,2],[10,9,2,2]],
[[-7,-3,3,2],[7,3,3,2],[-3,7,2,3],[3,-7,2,3],[0,0,2,2]],
[[0,-7,7,1],[0,7,7,1],[-8,0,2,2],[8,0,2,2],[0,0,2,2]],
[[-7,0,1.6,9],[7,0,1.6,9],[-1,-8,3,1],[1,8,3,1]],
[[-5,-5,2,2],[5,-5,2,2],[-5,5,2,2],[5,5,2,2],[0,-10,5,1],[0,10,5,1]]];
const MISSIONS=[
 {title:'Порт: доставьте батарею',type:'carry',count:8,mix:{normal:.85,fast:.15}},
 {title:'Квартал: включите передатчик',type:'charge',count:10,mix:{normal:.7,fast:.3}},
 {title:'Завод: обороняйте ядро',type:'defend',count:13,mix:{normal:.6,fast:.3,grabber:.1}},
 {title:'Лабиринт: доставьте образец',type:'carry',count:15,mix:{normal:.5,fast:.32,grabber:.12,screamer:.06}},
 {title:'Арена: уничтожьте босса',type:'boss',count:9,mix:{normal:.6,fast:.4}},
 {title:'Пустыня: почините насос',type:'charge',count:19,mix:{normal:.42,fast:.3,tank:.1,grabber:.1,screamer:.08}},
 {title:'Склад: спасите груз',type:'carry',count:22,mix:{normal:.38,fast:.32,tank:.12,grabber:.1,screamer:.08}},
 {title:'Станция: удержите реактор',type:'defend',count:26,mix:{normal:.32,fast:.3,tank:.2,grabber:.1,screamer:.08}},
 {title:'Метро: включите связь',type:'charge',count:30,mix:{normal:.25,fast:.35,tank:.14,grabber:.14,screamer:.12}},
 {title:'Финал: эвакуация',type:'evac',count:34,mix:{normal:.22,fast:.36,tank:.16,grabber:.12,screamer:.14}}];
const TRAP_NAMES=['Кран порта','Газовый вентиль','Промышленный пресс','Разрядник лабиринта','Неоновая катушка','Мина блокпоста','Криоловушка','Электроразряд','Поездовой сброс','Импульс арены'];
const EVENT_NAMES=['Кран открыл контейнеры','Сирена передатчика','Конвейер запущен','Свет в лабиринте погас','Босс выходит на арену','Насос поднял пыль','Лёд трескается','Реактор вышел на мощность','Приближается поезд','Сигнал эвакуации отправлен'];
const GUNS=[{damage:22,cool:.3,mag:12,reload:1.2,pellets:1,spread:.02,range:30},{damage:13,cool:.8,mag:6,reload:1.9,pellets:7,spread:.22,range:15},{damage:11,cool:.1,mag:30,reload:1.8,pellets:1,spread:.08,range:26}];
const clients=new Map(),players=new Map();let mode='duel',lobbyMode='duel',map=0,round=1,phase='lobby',rotate=true,difficulty=1,remaining=0,spawnAt=0,intermission=0,mission=null,bossMade=false,enemies=[],bullets=[],pickups=[],hazards=[],movers=[],fx=[],sequence=0,message='',messageUntil=0,upgrades={damage:0,armor:0},votes=new Map();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),rnd=(a,b)=>a+Math.random()*(b-a),live=()=>[...players.values()].filter(p=>p.alive),connected=()=>[...clients.values()].filter(c=>c.id>0).length;
function note(s,seconds=3){message=s;messageUntil=Date.now()+seconds*1000}
function collision(x,z,r=.45){return Math.abs(x)>28-r||Math.abs(z)>20-r||MAPS[map].some(([a,b,w,h])=>Math.abs(x-a)<w/2+r&&Math.abs(z-b)<h/2+r)}
function move(o,x,z,r=.45){if(!collision(x,o.z,r))o.x=x;if(!collision(o.x,z,r))o.z=z}
function freeNear(x,z){for(let radius=0;radius<15;radius+=1.5)for(let a=0;a<12;a++){const px=x+Math.cos(a*Math.PI/6)*radius,pz=z+Math.sin(a*Math.PI/6)*radius;if(!collision(px,pz,1.1))return{x:px,z:pz}}return{x:-16,z:0}}
function getId(){let n=1;while([...clients.values()].some(c=>c.id===n))n++;return n}
function makePlayer(id,score=0){const pos=mode==='duel'?{x:id===1?-16:16,z:0}:freeNear(id%2?-12:12,(id%5-2)*3);return{id,...pos,angle:id===1?Math.PI/2:-Math.PI/2,hp:100,alive:true,permadead:false,score,weapon:0,mags:GUNS.map(g=>g.mag),reserves:[null,24,120],cool:0,reload:0,reloadSlot:0,dash:0,dashTime:0,inv:1.2,hit:0,stun:0,stunGuard:0,carry:false,downed:false,bleed:0,revive:0,reviveTarget:null,input:{},lastAction:false,lastDash:false,lastReload:false}}
function clearRound(){enemies=[];bullets=[];pickups=[];hazards=[];movers=[];fx=[];bossMade=false;mission=null}
function resetRound(){const scores=new Map([...players.values()].map(p=>[p.id,p.score]));const dead=new Set([...players.values()].filter(p=>p.permadead).map(p=>p.id));players.clear();clearRound();for(const id of [...clients.values()].map(c=>c.id).filter(id=>id>0&&(mode==='zombie'||id<=2)).sort((a,b)=>a-b)){const p=makePlayer(id,scores.get(id)||0);if(dead.has(id)&&mode==='zombie'){p.alive=false;p.permadead=true;p.hp=0}players.set(id,p)}if(mode==='zombie'){const def=MISSIONS[round-1];remaining=Math.round(def.count*difficulty*1.45*(1+.40*Math.max(0,players.size-1)));spawnAt=0;const from=freeNear(-20,-13),to=freeNear(20,14),device=freeNear(0,-15);mission={type:def.type,title:def.title,from,to,at:def.type==='defend'||def.type==='charge'?device:to,progress:0,required:def.type==='defend'?22:def.type==='charge'?12:def.type==='evac'?8:1,delivered:false,carrier:null,hp:100,active:false,threat:false,prepare:def.type==='boss'?4:0,entry:null,trainTimer:0,event:EVENT_NAMES[map],trap:{...freeNear(-2,10),name:TRAP_NAMES[map],cooldown:0,flash:0},nodes:[],completedNodes:0};setupWorld()}phase='playing';note(mode==='duel'?`Раунд ${round}`:`Миссия ${round}/10: ${MISSIONS[round-1].title}`,4)}
function start(data){if(!['lobby','finished'].includes(phase))return;const requested=data.mode==='zombie'?'zombie':'duel';if(requested==='duel'&&(connected()<2||![...clients.values()].some(c=>c.id===2)))return;if(requested==='zombie'&&connected()<1)return;mode=requested;lobbyMode=requested;map=requested==='zombie'?0:clamp(Number(data.map)||0,0,9);rotate=requested==='zombie'?true:data.rotate!==false;difficulty=[.8,1,1.3].includes(data.difficulty)?data.difficulty:1;round=1;upgrades={damage:0,armor:0};votes.clear();players.clear();resetRound()}
function backLobby(){phase='lobby';clearRound();players.clear();mission=null;remaining=0;note('Ожидание игроков',999)}
function finishMission(){if(phase!=='playing')return;if(round>=10){phase='finished';note('Все миссии выполнены! Победа!',999)}else{phase='intermission';intermission=6;votes.clear();note('Выберите командный бонус: урон или броня · 6 секунд',6);for(const p of live())p.hp=Math.min(100,p.hp+25)}}
function resolveVotes(){let damage=0,armor=0;for(const choice of votes.values())if(choice==='damage')damage++;else armor++;upgrades[damage>=armor?'damage':'armor']++;votes.clear()}
function reload(p){const i=p.weapon,g=GUNS[i];if(p.reload||p.mags[i]>=g.mag||i&&p.reserves[i]<=0)return;p.reload=g.reload;p.reloadSlot=i}
function shoot(p){if(!p.alive||p.cool||p.reload||p.stun>0)return;const g=GUNS[p.weapon];if(!p.mags[p.weapon]){reload(p);return}p.cool=g.cool;p.mags[p.weapon]--;for(let i=0;i<g.pellets;i++){const a=p.angle+rnd(-g.spread,g.spread);bullets.push({id:++sequence,owner:p.id,x:p.x+Math.sin(a)*.69,z:p.z-Math.cos(a)*.69,vx:Math.sin(a)*35,vz:-Math.cos(a)*35,life:g.range/35,damage:g.damage*(1+.12*upgrades.damage)})}if(!p.mags[p.weapon])reload(p)}
function spawn(type){for(let n=0;n<40;n++){const side=mission?.threat&&mission.entry!==null&&Math.random()<.78?mission.entry:Math.floor(Math.random()*4),x=side<2?(side?-26:26):rnd(-26,26),z=side>1?(side===2?-18:18):rnd(-18,18);if(collision(x,z,.9)||live().some(p=>Math.hypot(x-p.x,z-p.z)<6))continue;
 const boss=type==='boss',tank=type==='tank',fast=type==='fast',screamer=type==='screamer',grabber=type==='grabber';
 const hp=(boss?520+90*Math.max(0,players.size-1):tank?100:fast?38:screamer?45:grabber?40:55)*difficulty;
 enemies.push({id:++sequence,x,z,hp,max:hp,type,r:boss?.85:tank?.62:.41,speed:(boss?1.8:tank?1.35:fast?3.1:screamer?1.9:grabber?2.3:2)*Math.sqrt(difficulty),damage:boss?24:tank?22:fast?9:screamer?7:grabber?8:13,attack:0,windup:0,slam:0,armor:boss?180*difficulty:0,gauge:0,gaugeMax:100,stun:0,screamCd:6,lungeCd:0,lunge:0,chargeCd:4,chargeWind:0,chargeDir:[0,0],chargeDash:0,hit:0,armed:!boss&&Math.random()<.30,gunCd:rnd(1.5,3.2),gunWind:0,aimDir:[0,0]});return true}return false}
function pickType(){const mix=MISSIONS[round-1].mix,roll=Math.random();let acc=0;for(const [t,w] of Object.entries(mix)){acc+=w;if(roll<=acc)return t}return'normal'}
function hurt(p,dmg,stunSec=0,raw=false){if(!p.alive||p.inv>0)return;p.hp=Math.max(0,p.hp-(raw?dmg:dmg*(1-.07*Math.min(8,upgrades.armor))));p.hit++;p.inv=.27;if(stunSec>0&&p.stunGuard<=0){p.stun=Math.max(p.stun,stunSec);p.stunGuard=2}if(p.hp)return;if(mode==='zombie'){p.alive=false;p.downed=true;p.bleed=22;p.hp=0;p.stun=0;if(p.carry&&mission){mission.carrier=null;p.carry=false;mission.from={x:p.x,z:p.z}}note(`Игрок ${p.id} ранен · удерживайте E рядом 2.5 секунды`,3);if(!live().length){phase='finished';note(`Поражение на миссии ${round}`,999)}return}p.alive=false;if(p.carry&&mission){mission.carrier=null;p.carry=false;mission.from={x:p.x,z:p.z}}if(mode==='duel'){const winner=[...players.values()].find(q=>q.id!==p.id);if(winner){winner.score++;if(winner.score>=7){phase='finished';note(`Победил игрок ${winner.id}!`,999)}else{phase='intermission';intermission=2.5;note(`Раунд взял игрок ${winner.id}`)}}}else if(!live().length){phase='finished';note(`Поражение на миссии ${round}`,999)}}
function kill(e){const ix=enemies.indexOf(e);if(ix<0)return;enemies.splice(ix,1);burst(e.x,e.z,e.type==='boss'?'bossdeath':e.type==='tank'?'bigdeath':'death',e.type==='boss'?2.2:e.type==='tank'?1.3:.8);if(Math.random()<.27)pickups.push({id:++sequence,x:e.x,z:e.z,type:Math.random()<.45?'heal':'ammo',age:0});if(e.type==='boss')note('Босс уничтожен · зачистите оставшихся врагов',3)}

const NODE_LABELS=[['Переключатель крана','Крюк'],['Антенна A','Антенна B','Питание'],['Лента конвейера','Аварийный рубильник'],['Маяк сектора 1','Маяк сектора 2'],[],['Деталь насоса','Охладитель','Клапан'],['Замок склада','Подъёмник'],['Трансформатор A','Трансформатор B','Щит'],['Рычаг платформы','Сигнальный блок','Питание поезда'],['Сигнал A','Сигнал B','Ворота']];
function burst(x,z,kind='explosion',power=1){fx.push({id:++sequence,x,z,kind,power,age:0})}
function setupWorld(){const locations=[[-21,12],[19,-14],[22,13],[-21,-14]];mission.nodes=NODE_LABELS[round-1].map((name,i)=>({id:i,name,...freeNear(...locations[(i+map)%4]),done:false}));hazards=[];movers=[];for(let i=0;i<6;i++){const a=i*2.399+map*.83,r=10+(i%3)*4,point=freeNear(Math.cos(a)*r,Math.sin(a)*r);if([mission.from,mission.to,mission.at,mission.trap,...mission.nodes].some(q=>dist(point,q)<3.5))continue;hazards.push({id:i,x:point.x,z:point.z,r:1.6,windup:0,cooldown:3+i*.6})}for(let i=0;i<2;i++)movers.push({id:i,x:i?-22:22,z:i?16:-16,w:2.8,d:2.4,lethal:false,warning:false,clock:i*.2,pause:0,side:i})}
function permanentDeath(p){if(!p.alive)return;p.hp=0;p.alive=false;p.downed=false;p.permadead=true;p.hit++;burst(p.x,p.z,'explosion',1.4);if(p.carry&&mission){p.carry=false;mission.carrier=null;mission.from={x:p.x,z:p.z}}note(`Игрок ${p.id} погиб от механизма и выбывает до конца матча!`,4);if(!live().length){phase='finished';note('Все игроки погибли. Поражение!',999)}}
function updateWorld(dt){if(!mission?.threat)return;for(const hazard of hazards){hazard.cooldown=Math.max(0,hazard.cooldown-dt);if(hazard.windup>0){hazard.windup-=dt;if(hazard.windup<=0){burst(hazard.x,hazard.z,'explosion',1.1);for(const p of live())if(dist(p,hazard)<hazard.r)hurt(p,50,0,true);hazard.cooldown=8}continue}if(hazard.cooldown<=0&&live().some(p=>dist(p,hazard)<hazard.r)){hazard.windup=.8;note('Мина активирована! Уходите из красного круга!',.8)}}for(const mv of movers){if(mv.pause>0){mv.pause-=dt;mv.lethal=false;mv.warning=false;continue}mv.clock+=dt;const cycle=mv.clock%6;mv.warning=cycle>=1.2&&cycle<2.2;mv.lethal=cycle>=2.2&&cycle<4.8;mv.x=clamp(mv.side?-22+44*((cycle-2.2)/2.6):22-44*((cycle-2.2)/2.6),-22,22);if(mv.lethal)for(const p of live())if(Math.abs(p.x-mv.x)<mv.w/2+.3&&Math.abs(p.z-mv.z)<mv.d/2+.3)permanentDeath(p)}}
function beginThreat(m){if(m.threat)return;m.threat=true;m.entry=(map+round+Math.floor(Math.random()*4))%4;spawnAt=2;note(`${m.event} · заражённые идут из отмеченного прохода!`,3)}
function interact(p){if(!mission||!p.alive||p.stun>0)return;const m=mission;const node=m.nodes?.find(q=>!q.done&&dist(p,q)<2.5);if(node){node.done=true;m.completedNodes++;burst(node.x,node.z,'spark',.7);for(const mv of movers){mv.pause=Math.max(mv.pause,5);mv.clock=0}if(map===0)m.trap.cooldown=0;if(map===2||map===7)m.hp=Math.min(100,m.hp+20);if(map===3)for(const mine of hazards)mine.cooldown=Math.max(mine.cooldown,12);if(map===9)m.required=Math.max(5,m.required-.7);if(map===1||map===8){m.trainTimer=2;note(`${node.name}: сирена привлекает быстрых зомби!`,2)}else note(`${node.name} активирован · механизмы остановлены на 5 секунд`,3);return}if(m.trap&&dist(p,m.trap)<2.4&&m.trap.cooldown<=0){m.trap.cooldown=18;m.trap.flash=1.2;burst(m.trap.x,m.trap.z,'trap',1.3);const power=map===6?55:map===2||map===9?130:88;for(const e of [...enemies])if(dist(e,m.trap)<4.6){e.hit++;if(e.type==='boss'){e.gauge=Math.min(e.gaugeMax,e.gauge+25)}else{e.hp-=power;e.stun=Math.max(e.stun,1.2);if(map===6)e.slow=3.5;if(e.hp<=0)kill(e)}}note(`${m.trap.name}: ловушка сработала!`,2);return}if(m.type==='evac'&&!m.threat&&dist(p,m.from)<2.6){beginThreat(m);return}if(m.type==='carry'){if(!m.carrier&&!m.delivered&&dist(p,m.from)<2.2){m.carrier=p.id;p.carry=true;beginThreat(m);note(`Игрок ${p.id} несёт груз · берегите носителя`,2)}else if(m.carrier===p.id&&dist(p,m.to)<2.4){p.carry=false;m.carrier=null;m.delivered=true;m.progress=1;note('Груз доставлен · зачистите арену',3)}}else if(m.type==='charge'&&dist(p,m.at)<2.6){beginThreat(m);m.progress=Math.min(m.required,m.progress+1);m.active=true;if(map===1&&m.progress%3===0)spawn('fast');if(map===8&&m.progress===Math.ceil(m.required/2)){m.trainTimer=2;note('Поезд идёт! Усиленная волна через 2 секунды',2)}if(m.progress>=m.required)note('Генератор запущен · зачистите арену',3)}}
function bossAI(e,dt,m){const targets=live();if(!targets.length)return;let target=targets[0];for(const p of targets)if(dist(e,p)<dist(e,target))target=p;if(e.hp<e.max*.35){if(m.carrier)target=players.get(m.carrier)||target;else if(['defend','charge'].includes(m.type)&&!m.threat)target=target;else if(['defend','charge'].includes(m.type))target={...m.at,id:'obj'}}
 if(e.stun>0){return}
 const d=dist(e,target),dx=(target.x-e.x)/Math.max(d,.001),dz=(target.z-e.z)/Math.max(d,.001);
 if(e.windup>0){e.windup-=dt;if(e.windup<=0){burst(e.x,e.z,'slam',1.6);for(const p of live())if(dist(e,p)<3.45)hurt(p,38,.5);note('Удар босса!',1);e.attack=3.2}return}
 if(e.chargeWind>0){e.chargeWind-=dt;if(e.chargeWind<=0){e.chargeDash=.5;note('Босс прямой таран!',1)}return}
 if(e.chargeDash>0){e.chargeDash-=dt;move(e,e.x+e.chargeDir[0]*18*dt,e.z+e.chargeDir[1]*18*dt,e.r);for(const p of live())if(Math.abs((p.x-e.x)*e.chargeDir[1]-(p.z-e.z)*e.chargeDir[0])<1.2&&dist(p,e)<2.4)hurt(p,26,.6);for(const q of live())if(dist(q,e)<1.6)hurt(q,26,.6);return}
 e.chargeCd-=dt;
 if(e.armor<=0&&e.chargeCd<=0&&d>4.5&&target.id!=='obj'){e.chargeWind=.9;e.chargeDir=[dx,dz];e.chargeCd=6.5;note('Босс готовит таран по линии!',1);return}
 if(d<3.2&&!e.attack){e.windup=.5;e.slam=3.45;note('Босс замахивается — отойдите!',.7);return}
 if(d>e.r+.5)move(e,e.x+dx*e.speed*dt,e.z+dz*e.speed*dt,e.r);else if(!e.attack){hurt(target,24);e.attack=1.3}}
function simulate(dt){if(phase==='intermission'){intermission-=dt;if(intermission<=0){resolveVotes();round++;if(rotate)map=(map+1)%10;resetRound()}return}if(phase!=='playing')return;
for(const p of players.values()){p.cool=Math.max(0,p.cool-dt);p.inv=Math.max(0,p.inv-dt);p.dash=Math.max(0,p.dash-dt);p.stun=Math.max(0,p.stun-dt);p.stunGuard=Math.max(0,p.stunGuard-dt);if(p.reload>0){p.reload-=dt;if(p.reload<=0){p.reload=0;const i=p.reloadSlot,qty=i?Math.min(GUNS[i].mag-p.mags[i],p.reserves[i]):GUNS[i].mag-p.mags[i];p.mags[i]+=qty;if(i)p.reserves[i]-=qty}}if(p.downed){p.bleed-=dt;if(p.bleed<=0){p.downed=false;p.revive=0;p.reviveTarget=null}continue}if(!p.alive)continue;const c=p.input;if(c.weapon!==undefined&&c.weapon!==p.weapon){p.weapon=c.weapon;p.reload=0}if(c.reload&&!p.lastReload)reload(p);p.lastReload=!!c.reload;if(c.dash&&!p.lastDash&&!p.dash&&p.stun<=0){p.dash=3;p.dashTime=.17;p.inv=Math.max(p.inv,.18)}p.lastDash=!!c.dash;const fallen=[...players.values()].filter(q=>q.downed&&q.id!==p.id&&dist(p,q)<2.2).sort((a,b)=>dist(p,a)-dist(p,b))[0];if(c.action&&fallen){if(p.reviveTarget!==fallen.id){p.revive=0;p.reviveTarget=fallen.id}p.revive+=dt;if(p.revive>=2.5){fallen.downed=false;fallen.alive=true;fallen.hp=45;fallen.inv=1.6;p.revive=0;p.reviveTarget=null;note(`Игрок ${fallen.id} поднят!`,2)}}else{p.revive=0;p.reviveTarget=null;if(c.action&&!p.lastAction)interact(p)}p.lastAction=!!c.action;const dx=Number(!!c.right)-Number(!!c.left),dz=Number(!!c.down)-Number(!!c.up),length=Math.hypot(dx,dz)||1,spd=p.stun>0?0:p.dashTime>0?14:p.carry?(map===6?3.5:4.25):5.1;move(p,p.x+dx/length*spd*dt,p.z+dz/length*spd*dt);p.dashTime=Math.max(0,p.dashTime-dt);const targets=mode==='duel'?[...players.values()].filter(q=>q.alive&&q.id!==p.id):enemies;let nearest=null,best=Infinity;for(const t of targets){const d=dist(p,t);if(d<best){best=d;nearest=t}}if(nearest)p.angle=Math.atan2(nearest.x-p.x,-(nearest.z-p.z));if(c.shoot)shoot(p)}
for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];let hit=false;const steps=Math.max(1,Math.ceil(35*dt/.19));for(let j=0;j<steps;j++){const x=b.x+b.vx*dt/steps,z=b.z+b.vz*dt/steps;if(collision(x,z,.04)){hit=true;break}b.x=x;b.z=z;if(b.owner<0){for(const p of live())if(dist(b,p)<.48){hurt(p,b.damage);hit=true;break}}else if(mode==='duel'){for(const p of players.values())if(p.alive&&p.id!==b.owner&&dist(b,p)<.48){hurt(p,b.damage);hit=true;break}}else for(const e of [...enemies])if(dist(b,e)<e.r+.13){e.hit++;if(e.type==='boss'){if(e.stun>0)e.hp-=b.damage;else{e.gauge=Math.min(e.gaugeMax,e.gauge+1);const reduction=e.armor>0?.5:1;e.hp-=b.damage*reduction;if(e.armor>0){const absorbed=Math.min(e.armor,b.damage*.3);e.armor-=absorbed}if(e.gauge>=e.gaugeMax){e.gauge=0;e.gaugeMax*=1.5;e.stun=3;e.armor=0;e.windup=0;e.chargeWind=0;burst(e.x,e.z,'stunburst',1.8);note('БОСС ОГЛУШЁН · 3 секунды максимального урона!',3)}}}else e.hp-=b.damage;if(e.hp<=0)kill(e);hit=true;break}if(hit)break}b.life-=dt;if(hit||b.life<=0)bullets.splice(i,1)}if(phase!=='playing')return;
if(mode==='zombie'){const m=mission;updateWorld(dt);if(phase!=='playing')return;
 if(m.type==='boss'&&!m.threat){m.prepare-=dt;if(m.prepare<=0)beginThreat(m)}
 if(m.trainTimer>0){m.trainTimer-=dt;if(m.trainTimer<=0){for(let k=0;k<5;k++)spawn('fast');burst(0,0,'trainhit',1.5);note('Поезд прибыл · быстрые зомби прорвались!',3)}}
 if(m.trap){m.trap.cooldown=Math.max(0,m.trap.cooldown-dt);m.trap.flash=Math.max(0,m.trap.flash-dt)}
 const cap=Math.min(82,Math.round(32+12*Math.sqrt(Math.max(1,players.size))));
 if(m.threat&&remaining>0){spawnAt-=dt;if(spawnAt<=0&&enemies.length<cap){if(spawn(pickType()))remaining--;spawnAt=Math.max(.32,1.04-round*.06)/Math.sqrt(Math.max(1,players.size/2))/difficulty}}
 if(m.type==='boss'&&m.threat&&!bossMade&&remaining<=Math.round(MISSIONS[round-1].count*difficulty*.4)){if(spawn('boss')){bossMade=true;note('Босс: броня, таран и удар по площади! Уходите от сигналов',4)}}
 for(const e of [...enemies]){e.attack=Math.max(0,e.attack-dt);e.slow=Math.max(0,(e.slow||0)-dt);e.stun=Math.max(0,e.stun-dt);if(e.type==='boss'){bossAI(e,dt,m);continue}if(e.stun>0)continue;
  if(e.armed){e.gunCd=Math.max(0,e.gunCd-dt);if(e.gunWind>0){e.gunWind-=dt;if(e.gunWind<=0){const [vx,vz]=e.aimDir;bullets.push({id:++sequence,owner:-e.id,x:e.x+vx*.72,z:e.z+vz*.72,vx:vx*17,vz:vz*17,life:1.35,damage:12});burst(e.x+vx*.72,e.z+vz*.72,'muzzle',.5)}continue}let goal=null;for(const p of live())if(!goal||dist(p,e)<dist(goal,e))goal=p;if(goal&&dist(goal,e)<15&&e.gunCd<=0){const d=Math.max(.01,dist(goal,e));e.aimDir=[(goal.x-e.x)/d,(goal.z-e.z)/d];e.gunWind=.55;e.gunCd=rnd(3.2,5.2);continue}}
  const targets=live();if(!targets.length)break;let closest=targets[0];for(const p of targets)if(dist(e,p)<dist(e,closest))closest=p;const d=dist(e,closest),dx=(closest.x-e.x)/Math.max(d,.001),dz=(closest.z-e.z)/Math.max(d,.001);
  if(e.type==='screamer'){e.screamCd-=dt;if(e.screamCd<=0&&d<12){if(e.windup>0){e.windup-=dt;if(e.windup<=0){for(let k=0;k<3;k++)spawn('normal');remaining+=0;e.screamCd=14;note('Крикун зовёт подкрепление!',1.6)}}else{e.windup=1.2;note('Крикун собирается кричать · прервите его!',1.2)}continue}}
  if(e.type==='grabber'){e.lungeCd-=dt;if(e.lunge>0){e.lunge-=dt;move(e,e.x+e.chargeDir[0]*9*dt,e.z+e.chargeDir[1]*9*dt,e.r);if(d<1.1&&!e.windup){hurt(closest,8,1.6);e.windup=1.3;note(`Игрок ${closest.id} схвачен · стреляйте в хватателя!`,1.4)}continue}if(e.windup>0){e.windup-=dt;continue}if(e.lungeCd<=0&&d>2&&d<6.5){e.lunge=.35;e.chargeDir=[dx,dz];e.lungeCd=7;note('Хвататель рвётся вперёд!',1)}continue}
  if(d>e.r+.5)move(e,e.x+dx*e.speed*(e.slow>0?.48:1)*dt,e.z+dz*e.speed*(e.slow>0?.48:1)*dt,e.r);else if(!e.attack){hurt(closest,e.damage);e.attack=.85}}
 if(m.type==='defend'){const close=live().some(p=>dist(p,m.at)<2.55);if(close&&!m.threat)beginThreat(m);m.active=close&&m.threat;if(close&&m.threat)m.progress=Math.min(m.required,m.progress+dt);if(enemies.some(e=>dist(e,m.at)<2.25))m.hp=Math.max(0,m.hp-3*dt);if(m.hp<=0){phase='finished';note('Реактор разрушен. Поражение!',999)}}
 if(m.type==='evac'){const already=m.active;m.active=m.threat&&remaining===0&&enemies.length===0;if(m.active&&!already)burst(m.at.x,m.at.z,'firework',1.6);if(m.active&&live().some(p=>dist(p,m.at)<2.4)){m.progress=Math.min(m.required,m.progress+dt);if(Math.random()<dt*.6)burst(m.at.x+rnd(-2,2),m.at.z+rnd(-2,2),'firework',.9)}}
 if(m.carrier){const carrier=players.get(m.carrier);if(carrier){m.from={x:carrier.x,z:carrier.z}}}
 if(phase==='playing'&&m.threat&&m.completedNodes===m.nodes.length&&remaining===0&&enemies.length===0){if(m.type==='boss'&&bossMade||m.type==='carry'&&m.delivered||m.type==='charge'&&m.progress>=m.required||m.type==='defend'&&m.progress>=m.required||m.type==='evac'&&m.progress>=m.required)finishMission()}}
for(let i=fx.length-1;i>=0;i--){fx[i].age+=dt;if(fx[i].age>1.6)fx.splice(i,1)}for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.age+=dt;for(const user of live())if(dist(p,user)<.85){if(p.type==='heal')user.hp=Math.min(100,user.hp+35);else{user.reserves[1]+=12;user.reserves[2]+=50}p.age=999;break}if(p.age>25)pickups.splice(i,1)}}
function state(){return JSON.stringify({type:'state',mode,lobbyMode,connected:connected(),map,round,phase,remaining,hazards:hazards.map(q=>({id:q.id,x:q.x,z:q.z,r:q.r,windup:q.windup,cooldown:q.cooldown})),movers:movers.map(q=>({id:q.id,x:q.x,z:q.z,w:q.w,d:q.d,lethal:q.lethal,warning:q.warning})),fx:fx.map(q=>({id:q.id,x:q.x,z:q.z,kind:q.kind,power:q.power,age:q.age})),upgrades,votes:Object.fromEntries(votes),notice:Date.now()<messageUntil?message:'',mission:mission&&{...mission},players:[...players.values()].map(p=>({id:p.id,x:p.x,z:p.z,angle:p.angle,hp:p.hp,alive:p.alive,score:p.score,weapon:p.weapon,mags:p.mags,reserves:p.reserves,reload:p.reload,dash:p.dash,hit:p.hit,stun:p.stun,permadead:p.permadead,carry:p.carry,downed:p.downed,bleed:p.bleed,revive:p.revive})),enemies:enemies.map(e=>({id:e.id,x:e.x,z:e.z,hp:e.hp,max:e.max,type:e.type,armor:e.armor,gauge:e.gauge,gaugeMax:e.gaugeMax,stun:e.stun,hit:e.hit,armed:e.armed,gunWind:e.gunWind,aimDir:e.aimDir,windup:e.windup,slam:e.slam,chargeWind:e.chargeWind,chargeDir:e.chargeDir})),bullets:bullets.map(b=>({id:b.id,x:b.x,z:b.z,owner:b.owner})),pickups})}
function send(ws,data){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data))}function all(){const data=state();for(const ws of clients.keys())if(ws.readyState===WebSocket.OPEN&&ws.bufferedAmount<150000)ws.send(data)}function welcome(ws,id){send(ws,{type:'welcome',id})}
function promote(){if(lobbyMode!=='duel'||!['lobby','finished'].includes(phase))return;for(const [ws,c] of clients)if(!c.id){const id=![...clients.values()].some(x=>x.id===1)?1:![...clients.values()].some(x=>x.id===2)?2:0;if(!id)break;c.id=id;welcome(ws,id)}}
const server=http.createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname;if(path==='/favicon.ico'){res.writeHead(204);res.end();return}if(!['/','/index.html','/three.module.js'].includes(path)){res.writeHead(404);res.end('Not found');return}try{const file=path==='/three.module.js'?'./node_modules/three/build/three.module.js':'./index.html';const data=await readFile(new URL(file,import.meta.url));res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-store'});res.end(data)}catch(e){console.error(e);res.writeHead(500);res.end('Check files and npm install')}});
const wss=new WebSocketServer({server,maxPayload:2048});wss.on('connection',(ws,req)=>{try{if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host){ws.close(1008);return}}catch{ws.close(1008);return}let id=lobbyMode==='zombie'?connected()<MAX?getId():0:![...clients.values()].some(c=>c.id===1)?1:![...clients.values()].some(c=>c.id===2)?2:0;clients.set(ws,{id});welcome(ws,id);if(id&&mode==='zombie'&&['playing','intermission'].includes(phase)){players.set(id,makePlayer(id));note(`Игрок ${id} подключился`,2)}all();ws.on('message',raw=>{if(raw.length>2048)return;let data;try{data=JSON.parse(raw)}catch{return}const c=clients.get(ws);if(!c?.id)return;if(data.type==='mode'&&c.id===1&&['lobby','finished'].includes(phase)){lobbyMode=data.mode==='zombie'?'zombie':'duel';if(lobbyMode==='zombie'){for(const [other,info] of clients)if(!info.id&&connected()<MAX){info.id=getId();welcome(other,info.id)}}else{for(const [other,info] of clients)if(info.id>2){info.id=0;welcome(other,0)}promote()}all()}else if(data.type==='start'&&c.id===1){start(data);all()}else if(data.type==='vote'&&phase==='intermission'&&players.has(c.id)&&['damage','armor'].includes(data.choice)){votes.set(c.id,data.choice);all()}else if(data.type==='input'&&players.has(c.id)){const q=data.keys||{};players.get(c.id).input={up:q.up===true,down:q.down===true,left:q.left===true,right:q.right===true,shoot:q.shoot===true,dash:q.dash===true,reload:q.reload===true,action:q.action===true,weapon:clamp(Number(q.weapon)||0,0,2)}}});ws.on('close',()=>{const c=clients.get(ws);clients.delete(ws);if(!c?.id)return;const p=players.get(c.id);if(p?.carry&&mission){mission.carrier=null;mission.from={x:p.x,z:p.z}}players.delete(c.id);if(c.id===1||mode==='duel'&&phase!=='lobby'||mode==='zombie'&&!players.size){backLobby();promote()}else if(phase==='lobby')promote();all()})});
let last=performance.now(),ticks=0;setInterval(()=>{const now=performance.now(),dt=Math.min((now-last)/1000,.045);last=now;simulate(dt);if(++ticks%2===0)all()},1000/60);
server.listen(PORT,'0.0.0.0',()=>{console.log(`DUO ARENA http://localhost:${PORT}`);for(const adapters of Object.values(networkInterfaces()))for(const a of adapters||[])if(a.family==='IPv4'&&!a.internal)console.log(`LAN http://${a.address}:${PORT}`)});
